# Generated by Django 5.2.4 on 2025-07-25 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leave", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="is_admin",
        ),
        migrations.AddField(
            model_name="employee",
            name="role",
            field=models.IntegerField(default=1),
        ),
    ]
