# Generated by Django 5.2.4 on 2025-07-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0004_appsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.IntegerField(choices=[(1, 'Normal Employee'), (2, 'Admin'), (3, 'Super Admin')], default=1),
        ),
    ]
